name: Pull Request Checks

on:
  pull_request:
    branches: [master]

concurrency:
  group: pr-checks-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  analyze-test:
    name: Analyze & Test  (ubuntu-latest)
    uses: ./.github/workflows/validate.yml
    with:
      os: ubuntu-latest
